version: '3.7'

services:
  xdbc-server:
    image: xdbc-server
    container_name: xdbcserver
    restart: always
    ports:
      - 1234:1234
      - 1235:1235
      - 1236:1236
      - 1237:1237
      - 1238:1238
    shm_size: '2gb'
    labels:
      com.docker-tc.enabled: 1


  xdbc-client:
    image: xdbc-client
    container_name: xdbcclient
    restart: always
    shm_size: '2gb'
    labels:
      com.docker-tc.enabled: 1

  postgres-1:
    image: postgresdb
    container_name: pg1
    restart: always
    volumes:
      - test-data:/data
      - pgvolume1:/var/lib/postgresql/
    ports:
      - 15432:5432
    shm_size: '2gb'

  clickhouse:
    #image: my/clickhouse-all-in-one
    image: clickhousedb
    container_name: ch
    privileged: true
    ports:
      - 19000:9000
      - 18123:8123
    volumes:
      - test-data:/data
      - chdbvol:/var/lib/clickhouse
    shm_size: '2gb'

volumes:
  test-data:
    external: true
  pgvolume1:
  chdbvol:

networks:
  default:
    name: polydb-net